In [20]:
import optuna
import joblib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score,StratifiedKFold
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, make_scorer, f1_score
from optuna.samplers import TPESampler



In [2]:
df = pd.read_csv('data/cancer-risk-factors-processed.csv')
df.head()

,Patient_ID,Cancer_Type,Age,Gender,Smoking,Alcohol_Use,Obesity,Family_History,Diet_Red_Meat,Diet_Salted_Processed,...,Physical_Activity,Air_Pollution,Occupational_Hazards,BRCA_Mutation,H_Pylori_Infection,Calcium_Intake,Overall_Risk_Score,BMI,Physical_Activity_Level,Risk_Level
0,LU0000,Breast,68,0,7,2,8,0,5,3,...,4,6,3,1,0,0,0.398696,28.0,5,Medium
1,LU0001,Prostate,74,1,8,9,8,0,0,3,...,1,3,3,0,0,5,0.424299,25.4,9,Medium
2,LU0002,Skin,55,1,7,10,7,0,3,3,...,1,8,10,0,0,6,0.605082,28.6,2,Medium
3,LU0003,Colon,61,0,6,2,2,0,6,2,...,6,4,8,0,0,8,0.318449,32.1,7,Low
4,LU0004,Lung,67,1,10,7,4,0,6,3,...,9,10,9,0,0,5,0.524358,25.1,2,Medium


In [3]:
X = df.drop(columns=['Risk_Level', 'Patient_ID', 'Cancer_Type'])

le = LabelEncoder()
y = le.fit_transform(df['Risk_Level'])

In [4]:
# Split into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [5]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [6]:
model_rf = RandomForestClassifier(random_state=42, n_estimators=100)
model_rf.fit(X_train, y_train)

,"random_state random_state: int, RandomState instance or None, default=NoneControls both the randomness of the bootstrapping of the samples usedwhen building trees (if ``bootstrap=True``) and the sampling of thefeatures to consider when looking for the best split at each node(if ``max_features < n_features``).See :term:`Glossary <random_state>` for details.",42
,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstr

In [7]:
y_pred = model_rf.predict(X_test)

print("Classification Report:\n", classification_report(y_test, y_pred, target_names=le.classes_))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Classification Report:
               precision    recall  f1-score   support

        High       1.00      0.95      0.97        20
         Low       1.00      1.00      1.00        65
      Medium       1.00      1.00      1.00       315

    accuracy                           1.00       400
   macro avg       1.00      0.98      0.99       400
weighted avg       1.00      1.00      1.00       400

Confusion Matrix:
 [[ 19   0   1]
 [  0  65   0]
 [  0   0 315]]


The model accurately distinguishes all risk levels, with only 1 mistake out of 400 with imbalanced dataset 

In [8]:
model_lr = LogisticRegression(random_state=42, max_iter=1000)
model_lr.fit(X_train, y_train)

,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",42
,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lb

In [9]:
y_pred_lr = model_lr.predict(X_test)

print("Classification Report:\n", classification_report(y_test, y_pred_lr, target_names=le.classes_))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))

Classification Report:
               precision    recall  f1-score   support

        High       1.00      0.80      0.89        20
         Low       0.97      0.95      0.96        65
      Medium       0.98      0.99      0.99       315

    accuracy                           0.98       400
   macro avg       0.98      0.92      0.95       400
weighted avg       0.98      0.98      0.98       400

Confusion Matrix:
 [[ 16   0   4]
 [  0  62   3]
 [  0   2 313]]


## Removing Overall_Risk_Score and retrying

In [10]:
X_new = df.drop(columns=['Risk_Level', 'Patient_ID', 'Cancer_Type', 'Overall_Risk_Score'])

le = LabelEncoder()
y_new = le.fit_transform(df['Risk_Level'])

In [11]:
# Split into training and testing sets

X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_new, y_new, test_size=0.2, random_state=42, stratify=y_new)

In [12]:
scaler = StandardScaler()
X_train_new = scaler.fit_transform(X_train_new)
X_test_new = scaler.transform(X_test_new)

In [13]:
model_rf_new = RandomForestClassifier(random_state=42, n_estimators=100)
model_rf_new.fit(X_train_new, y_train_new)

,"random_state random_state: int, RandomState instance or None, default=NoneControls both the randomness of the bootstrapping of the samples usedwhen building trees (if ``bootstrap=True``) and the sampling of thefeatures to consider when looking for the best split at each node(if ``max_features < n_features``).See :term:`Glossary <random_state>` for details.",42
,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstr

In [14]:
y_pred_new = model_rf_new.predict(X_test_new)

print("Classification Report:\n", classification_report(y_test_new, y_pred_new, target_names=le.classes_))
print("Confusion Matrix:\n", confusion_matrix(y_test_new, y_pred_new))


Classification Report:
               precision    recall  f1-score   support

        High       1.00      0.05      0.10        20
         Low       0.85      0.34      0.48        65
      Medium       0.83      0.99      0.90       315

    accuracy                           0.83       400
   macro avg       0.89      0.46      0.49       400
weighted avg       0.84      0.83      0.80       400

Confusion Matrix:
 [[  1   0  19]
 [  0  22  43]
 [  0   4 311]]


In [15]:
model_lr_new = LogisticRegression(random_state=42, max_iter=1000)
model_lr_new.fit(X_train_new, y_train_new)

,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",42
,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lb

In [16]:
y_pred_lr_new = model_lr_new.predict(X_test_new )

print("Classification Report:\n", classification_report(y_test_new, y_pred_lr_new, target_names=le.classes_))
print("Confusion Matrix:\n", confusion_matrix(y_test_new, y_pred_lr_new))

Classification Report:
               precision    recall  f1-score   support

        High       0.50      0.20      0.29        20
         Low       0.85      0.78      0.82        65
      Medium       0.91      0.96      0.93       315

    accuracy                           0.89       400
   macro avg       0.75      0.65      0.68       400
weighted avg       0.88      0.89      0.88       400

Confusion Matrix:
 [[  4   0  16]
 [  0  51  14]
 [  4   9 302]]


### SMOTE

In [17]:
smote = SMOTE(random_state=42)
resampled = smote.fit_resample(X_train_new, y_train_new)

X_train_res = resampled[0]
y_train_res = resampled[1]




In [18]:
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train_res, y_train_res)

,"random_state random_state: int, RandomState instance or None, default=NoneControls both the randomness of the bootstrapping of the samples usedwhen building trees (if ``bootstrap=True``) and the sampling of thefeatures to consider when looking for the best split at each node(if ``max_features < n_features``).See :term:`Glossary <random_state>` for details.",42
,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstr

In [19]:
y_pred_s = rf_model.predict(X_test_new)

print(f"Classification report:{classification_report(y_test_new, y_pred_s)}")
print(f"Confusion matrix: {confusion_matrix(y_test_new, y_pred_s)}")

Classification report:              precision    recall  f1-score   support

           0       0.62      0.25      0.36        20
           1       0.72      0.63      0.67        65
           2       0.88      0.94      0.91       315

    accuracy                           0.85       400
   macro avg       0.74      0.61      0.65       400
weighted avg       0.84      0.85      0.84       400

Confusion matrix: [[  5   0  15]
 [  0  41  24]
 [  3  16 296]]


- Accuracy: 84%
- High risk: 5 correctly classified, 15 mis-classified as Medium
- Low risk: 41 correctly classified, 24 confused with Medium.
- Medium risk: 296 correctly classfied, 19 confused as High/Low.
- Still struggler to detect High risk patients even with SMOTE.

In [21]:
# Define macro F1 scorer explicity for multiclass 
def macro_f1(y_true, y_pred):
    return f1_score(y_true, y_pred, average= 'macro')

scorer = make_scorer(macro_f1)

In [22]:
def objective(trial):
    params={
        'n_estimators': trial.suggest_int('n_estimators', 50, 500),
        'max_depth': trial.suggest_int('max_depth', 3, 30),
        'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 10),
        'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2']),
        'bootstrap': trial.suggest_categorical('bootstrap', [True, False]),
        'criterion': trial.suggest_categorical('criterion', ['gini', 'entropy']),
        'random_state': 42,
        'n_jobs': -1
    }

    model = RandomForestClassifier(**params)

    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
    scores = []

    for train_idx, val_idx in cv.split(X_train_res, y_train_res):
        X_t, X_v = X_train_res[train_idx], X_train_res[val_idx]
        y_t, y_v = y_train_res[train_idx], y_train_res[val_idx]
        
        model.fit(X_t, y_t)
        y_pred= model.predict(X_v)

        score = f1_score(y_v, y_pred, average="macro")
        scores.append(score)
    return np.mean(scores)

In [23]:
## Create study

sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, study_name='rf_macro_f1')

[I 2026-08-23 10:43:21,367] A new study created in memory with name: rf_macro_f1


In [24]:
# Run optimization

n_trials = 100 # Change to 100+ if you want to more thorough search
study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

print("Best trial: ")
print("Value(macro f1): ", study.best_value)
print("Params: ")
for k, v in study.best_params.items():
    print(f"{k}: {v}")

Best trial: 0. Best value: 0.944607:   1%|          | 1/100 [00:02<03:46,  2.29s/it]

[I 2026-08-23 10:46:30,511] Trial 0 finished with value: 0.944607455324415 and parameters: {'n_estimators': 218, 'max_depth': 29, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 0 with value: 0.944607455324415.


Best trial: 1. Best value: 0.948837:   2%|▏         | 2/100 [00:02<02:12,  1.35s/it]

[I 2026-08-23 10:46:31,208] Trial 1 finished with value: 0.9488367157392911 and parameters: {'n_estimators': 59, 'max_depth': 30, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 1 with value: 0.9488367157392911.


Best trial: 1. Best value: 0.948837:   3%|▎         | 3/100 [00:05<03:10,  1.96s/it]

[I 2026-08-23 10:46:33,894] Trial 2 finished with value: 0.9185777345721403 and parameters: {'n_estimators': 325, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 1 with value: 0.9488367157392911.


Best trial: 1. Best value: 0.948837:   4%|▍         | 4/100 [00:08<03:56,  2.46s/it]

[I 2026-08-23 10:46:37,119] Trial 3 finished with value: 0.9189867064795951 and parameters: {'n_estimators': 324, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 1 with value: 0.9488367157392911.


Best trial: 1. Best value: 0.948837:   5%|▌         | 5/100 [00:09<03:04,  1.94s/it]

[I 2026-08-23 10:46:38,132] Trial 4 finished with value: 0.9345633199628726 and parameters: {'n_estimators': 105, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 1 with value: 0.9488367157392911.


Best trial: 1. Best value: 0.948837:   6%|▌         | 6/100 [00:15<05:00,  3.20s/it]

[I 2026-08-23 10:46:43,770] Trial 5 finished with value: 0.938751382994755 and parameters: {'n_estimators': 487, 'max_depth': 24, 'min_samples_split': 10, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 1 with value: 0.9488367157392911.


Best trial: 1. Best value: 0.948837:   7%|▋         | 7/100 [00:18<04:51,  3.14s/it]

[I 2026-08-23 10:46:46,777] Trial 6 finished with value: 0.9466541977244985 and parameters: {'n_estimators': 225, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 1 with value: 0.9488367157392911.


Best trial: 1. Best value: 0.948837:   8%|▊         | 8/100 [00:24<06:07,  4.00s/it]

[I 2026-08-23 10:46:52,627] Trial 7 finished with value: 0.9263586837286195 and parameters: {'n_estimators': 398, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 1 with value: 0.9488367157392911.


Best trial: 8. Best value: 0.954072:   9%|▉         | 9/100 [00:31<07:18,  4.82s/it]

[I 2026-08-23 10:46:59,264] Trial 8 finished with value: 0.9540717718074476 and parameters: {'n_estimators': 439, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 8 with value: 0.9540717718074476.


Best trial: 8. Best value: 0.954072:  10%|█         | 10/100 [00:33<05:57,  3.98s/it]

[I 2026-08-23 10:47:01,345] Trial 9 finished with value: 0.938377989060207 and parameters: {'n_estimators': 103, 'max_depth': 22, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 8 with value: 0.9540717718074476.


Best trial: 8. Best value: 0.954072:  11%|█         | 11/100 [00:40<07:27,  5.03s/it]

[I 2026-08-23 10:47:08,762] Trial 10 finished with value: 0.9525258583151524 and parameters: {'n_estimators': 487, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 8 with value: 0.9540717718074476.


Best trial: 8. Best value: 0.954072:  12%|█▏        | 12/100 [00:48<08:33,  5.83s/it]

[I 2026-08-23 10:47:16,431] Trial 11 finished with value: 0.9519956330517996 and parameters: {'n_estimators': 492, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 8 with value: 0.9540717718074476.


Best trial: 12. Best value: 0.954393:  13%|█▎        | 13/100 [00:54<08:43,  6.01s/it]

[I 2026-08-23 10:47:22,861] Trial 12 finished with value: 0.9543929814867114 and parameters: {'n_estimators': 417, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 12 with value: 0.9543929814867114.


Best trial: 12. Best value: 0.954393:  14%|█▍        | 14/100 [01:00<08:40,  6.06s/it]

[I 2026-08-23 10:47:29,018] Trial 13 finished with value: 0.9492811162667758 and parameters: {'n_estimators': 405, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 12 with value: 0.9543929814867114.


Best trial: 12. Best value: 0.954393:  15%|█▌        | 15/100 [01:07<08:38,  6.10s/it]

[I 2026-08-23 10:47:35,221] Trial 14 finished with value: 0.9519281137995192 and parameters: {'n_estimators': 395, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 12 with value: 0.9543929814867114.


Best trial: 12. Best value: 0.954393:  16%|█▌        | 16/100 [01:12<08:08,  5.82s/it]

[I 2026-08-23 10:47:40,381] Trial 15 finished with value: 0.8229860768620642 and parameters: {'n_estimators': 331, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 12 with value: 0.9543929814867114.


Best trial: 12. Best value: 0.954393:  17%|█▋        | 17/100 [01:18<08:23,  6.06s/it]

[I 2026-08-23 10:47:47,020] Trial 16 finished with value: 0.9503390363360654 and parameters: {'n_estimators': 433, 'max_depth': 25, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 12 with value: 0.9543929814867114.


Best trial: 12. Best value: 0.954393:  18%|█▊        | 18/100 [01:22<07:25,  5.43s/it]

[I 2026-08-23 10:47:50,966] Trial 17 finished with value: 0.9521781106181262 and parameters: {'n_estimators': 252, 'max_depth': 19, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 12 with value: 0.9543929814867114.


Best trial: 12. Best value: 0.954393:  19%|█▉        | 19/100 [01:29<07:54,  5.86s/it]

[I 2026-08-23 10:47:57,844] Trial 18 finished with value: 0.9373199595106984 and parameters: {'n_estimators': 447, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 12 with value: 0.9543929814867114.


Best trial: 12. Best value: 0.954393:  20%|██        | 20/100 [01:34<07:33,  5.67s/it]

[I 2026-08-23 10:48:03,080] Trial 19 finished with value: 0.9466469393443583 and parameters: {'n_estimators': 352, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 12 with value: 0.9543929814867114.


Best trial: 20. Best value: 0.956759:  21%|██        | 21/100 [01:39<06:55,  5.26s/it]

[I 2026-08-23 10:48:07,384] Trial 20 finished with value: 0.9567586532116746 and parameters: {'n_estimators': 270, 'max_depth': 26, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 20 with value: 0.9567586532116746.


Best trial: 20. Best value: 0.956759:  22%|██▏       | 22/100 [01:43<06:25,  4.95s/it]

[I 2026-08-23 10:48:11,588] Trial 21 finished with value: 0.9562147391726873 and parameters: {'n_estimators': 276, 'max_depth': 27, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 20 with value: 0.9567586532116746.


Best trial: 20. Best value: 0.956759:  23%|██▎       | 23/100 [01:47<06:07,  4.77s/it]

[I 2026-08-23 10:48:15,955] Trial 22 finished with value: 0.9511172483999907 and parameters: {'n_estimators': 281, 'max_depth': 27, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 20 with value: 0.9567586532116746.


Best trial: 20. Best value: 0.956759:  24%|██▍       | 24/100 [01:50<05:16,  4.16s/it]

[I 2026-08-23 10:48:18,688] Trial 23 finished with value: 0.9556754223246519 and parameters: {'n_estimators': 170, 'max_depth': 26, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 20 with value: 0.9567586532116746.


Best trial: 20. Best value: 0.956759:  25%|██▌       | 25/100 [01:53<04:40,  3.75s/it]

[I 2026-08-23 10:48:21,471] Trial 24 finished with value: 0.9532419896737293 and parameters: {'n_estimators': 172, 'max_depth': 27, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 20 with value: 0.9567586532116746.


Best trial: 20. Best value: 0.956759:  26%|██▌       | 26/100 [01:55<04:13,  3.43s/it]

[I 2026-08-23 10:48:24,152] Trial 25 finished with value: 0.949268431531022 and parameters: {'n_estimators': 169, 'max_depth': 24, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 20 with value: 0.9567586532116746.


Best trial: 26. Best value: 0.957737:  27%|██▋       | 27/100 [01:58<03:57,  3.25s/it]

[I 2026-08-23 10:48:26,999] Trial 26 finished with value: 0.9577374080062966 and parameters: {'n_estimators': 176, 'max_depth': 27, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  28%|██▊       | 28/100 [02:02<04:12,  3.50s/it]

[I 2026-08-23 10:48:31,084] Trial 27 finished with value: 0.945000551345286 and parameters: {'n_estimators': 266, 'max_depth': 28, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  29%|██▉       | 29/100 [02:06<04:06,  3.47s/it]

[I 2026-08-23 10:48:34,466] Trial 28 finished with value: 0.9527417120603848 and parameters: {'n_estimators': 214, 'max_depth': 22, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  30%|███       | 30/100 [02:09<03:51,  3.31s/it]

[I 2026-08-23 10:48:37,419] Trial 29 finished with value: 0.9437748931372968 and parameters: {'n_estimators': 213, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  31%|███       | 31/100 [02:13<04:14,  3.69s/it]

[I 2026-08-23 10:48:41,998] Trial 30 finished with value: 0.9567134419850137 and parameters: {'n_estimators': 292, 'max_depth': 23, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  32%|███▏      | 32/100 [02:19<04:49,  4.26s/it]

[I 2026-08-23 10:48:47,574] Trial 31 finished with value: 0.9556488700252551 and parameters: {'n_estimators': 365, 'max_depth': 23, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  33%|███▎      | 33/100 [02:23<04:52,  4.36s/it]

[I 2026-08-23 10:48:52,168] Trial 32 finished with value: 0.9514036930318944 and parameters: {'n_estimators': 300, 'max_depth': 29, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  34%|███▍      | 34/100 [02:27<04:34,  4.16s/it]

[I 2026-08-23 10:48:55,872] Trial 33 finished with value: 0.9574944215659903 and parameters: {'n_estimators': 238, 'max_depth': 26, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  35%|███▌      | 35/100 [02:31<04:14,  3.92s/it]

[I 2026-08-23 10:48:59,227] Trial 34 finished with value: 0.9538853492289568 and parameters: {'n_estimators': 242, 'max_depth': 25, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  36%|███▌      | 36/100 [02:34<03:54,  3.67s/it]

[I 2026-08-23 10:49:02,309] Trial 35 finished with value: 0.9511538932317732 and parameters: {'n_estimators': 192, 'max_depth': 29, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  37%|███▋      | 37/100 [02:36<03:23,  3.23s/it]

[I 2026-08-23 10:49:04,521] Trial 36 finished with value: 0.953608891064151 and parameters: {'n_estimators': 145, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  38%|███▊      | 38/100 [02:40<03:47,  3.66s/it]

[I 2026-08-23 10:49:09,189] Trial 37 finished with value: 0.9519755439472152 and parameters: {'n_estimators': 305, 'max_depth': 25, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  39%|███▉      | 39/100 [02:42<03:12,  3.16s/it]

[I 2026-08-23 10:49:11,160] Trial 38 finished with value: 0.9552090131067564 and parameters: {'n_estimators': 138, 'max_depth': 21, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  40%|████      | 40/100 [02:44<02:33,  2.56s/it]

[I 2026-08-23 10:49:12,316] Trial 39 finished with value: 0.9556708361670991 and parameters: {'n_estimators': 62, 'max_depth': 30, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  41%|████      | 41/100 [02:47<02:53,  2.94s/it]

[I 2026-08-23 10:49:16,139] Trial 40 finished with value: 0.9452772836652209 and parameters: {'n_estimators': 235, 'max_depth': 28, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  42%|████▏     | 42/100 [02:52<03:16,  3.38s/it]

[I 2026-08-23 10:49:20,555] Trial 41 finished with value: 0.9543167602876265 and parameters: {'n_estimators': 277, 'max_depth': 26, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  43%|████▎     | 43/100 [02:57<03:39,  3.84s/it]

[I 2026-08-23 10:49:25,478] Trial 42 finished with value: 0.9566977139260765 and parameters: {'n_estimators': 308, 'max_depth': 27, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  44%|████▍     | 44/100 [03:02<03:52,  4.16s/it]

[I 2026-08-23 10:49:30,371] Trial 43 finished with value: 0.9564361517368835 and parameters: {'n_estimators': 305, 'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  45%|████▌     | 45/100 [03:07<04:05,  4.47s/it]

[I 2026-08-23 10:49:35,563] Trial 44 finished with value: 0.9527626276527204 and parameters: {'n_estimators': 330, 'max_depth': 26, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  46%|████▌     | 46/100 [03:10<03:41,  4.11s/it]

[I 2026-08-23 10:49:38,832] Trial 45 finished with value: 0.9566699708400389 and parameters: {'n_estimators': 203, 'max_depth': 28, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  47%|████▋     | 47/100 [03:14<03:30,  3.97s/it]

[I 2026-08-23 10:49:42,473] Trial 46 finished with value: 0.9533864778072686 and parameters: {'n_estimators': 255, 'max_depth': 22, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  48%|████▊     | 48/100 [03:19<03:50,  4.44s/it]

[I 2026-08-23 10:49:48,009] Trial 47 finished with value: 0.9482140348612509 and parameters: {'n_estimators': 354, 'max_depth': 23, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  49%|████▉     | 49/100 [03:24<03:48,  4.49s/it]

[I 2026-08-23 10:49:52,604] Trial 48 finished with value: 0.9519773927354528 and parameters: {'n_estimators': 294, 'max_depth': 25, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  50%|█████     | 50/100 [03:30<04:03,  4.86s/it]

[I 2026-08-23 10:49:58,353] Trial 49 finished with value: 0.954571238476345 and parameters: {'n_estimators': 373, 'max_depth': 28, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  51%|█████     | 51/100 [03:33<03:39,  4.49s/it]

[I 2026-08-23 10:50:01,953] Trial 50 finished with value: 0.9535660317112109 and parameters: {'n_estimators': 227, 'max_depth': 18, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  52%|█████▏    | 52/100 [03:36<03:16,  4.10s/it]

[I 2026-08-23 10:50:05,159] Trial 51 finished with value: 0.9564066288847939 and parameters: {'n_estimators': 202, 'max_depth': 27, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  53%|█████▎    | 53/100 [03:39<02:44,  3.50s/it]

[I 2026-08-23 10:50:07,258] Trial 52 finished with value: 0.9564286342416377 and parameters: {'n_estimators': 124, 'max_depth': 29, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  54%|█████▍    | 54/100 [03:42<02:35,  3.38s/it]

[I 2026-08-23 10:50:10,355] Trial 53 finished with value: 0.9524114227592458 and parameters: {'n_estimators': 190, 'max_depth': 26, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  55%|█████▌    | 55/100 [03:46<02:39,  3.54s/it]

[I 2026-08-23 10:50:14,258] Trial 54 finished with value: 0.9519442479440898 and parameters: {'n_estimators': 251, 'max_depth': 28, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  56%|█████▌    | 56/100 [03:50<02:42,  3.70s/it]

[I 2026-08-23 10:50:18,326] Trial 55 finished with value: 0.9470049330694633 and parameters: {'n_estimators': 263, 'max_depth': 24, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  57%|█████▋    | 57/100 [03:55<02:55,  4.07s/it]

[I 2026-08-23 10:50:23,278] Trial 56 finished with value: 0.9285426824540458 and parameters: {'n_estimators': 321, 'max_depth': 21, 'min_samples_split': 4, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  58%|█████▊    | 58/100 [03:59<02:57,  4.23s/it]

[I 2026-08-23 10:50:27,884] Trial 57 finished with value: 0.9551070060552802 and parameters: {'n_estimators': 289, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  59%|█████▉    | 59/100 [04:02<02:38,  3.85s/it]

[I 2026-08-23 10:50:30,856] Trial 58 finished with value: 0.952479366252225 and parameters: {'n_estimators': 186, 'max_depth': 27, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  60%|██████    | 60/100 [04:05<02:17,  3.44s/it]

[I 2026-08-23 10:50:33,343] Trial 59 finished with value: 0.9569101513144234 and parameters: {'n_estimators': 154, 'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  61%|██████    | 61/100 [04:06<01:51,  2.85s/it]

[I 2026-08-23 10:50:34,813] Trial 60 finished with value: 0.9531059566626624 and parameters: {'n_estimators': 100, 'max_depth': 24, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  62%|██████▏   | 62/100 [04:09<01:45,  2.77s/it]

[I 2026-08-23 10:50:37,398] Trial 61 finished with value: 0.9571983397916419 and parameters: {'n_estimators': 160, 'max_depth': 26, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  63%|██████▎   | 63/100 [04:11<01:39,  2.68s/it]

[I 2026-08-23 10:50:39,874] Trial 62 finished with value: 0.9571882871988922 and parameters: {'n_estimators': 156, 'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  64%|██████▍   | 64/100 [04:14<01:33,  2.61s/it]

[I 2026-08-23 10:50:42,313] Trial 63 finished with value: 0.9529954199125598 and parameters: {'n_estimators': 153, 'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  65%|██████▌   | 65/100 [04:16<01:24,  2.41s/it]

[I 2026-08-23 10:50:44,269] Trial 64 finished with value: 0.9569726617795841 and parameters: {'n_estimators': 118, 'max_depth': 22, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 26. Best value: 0.957737:  66%|██████▌   | 66/100 [04:17<01:12,  2.14s/it]

[I 2026-08-23 10:50:45,775] Trial 65 finished with value: 0.9503431889157464 and parameters: {'n_estimators': 84, 'max_depth': 21, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 26 with value: 0.9577374080062966.


Best trial: 66. Best value: 0.958038:  67%|██████▋   | 67/100 [04:19<01:08,  2.08s/it]

[I 2026-08-23 10:50:47,708] Trial 66 finished with value: 0.9580384091817499 and parameters: {'n_estimators': 116, 'max_depth': 26, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 66 with value: 0.9580384091817499.


Best trial: 66. Best value: 0.958038:  68%|██████▊   | 68/100 [04:21<01:04,  2.01s/it]

[I 2026-08-23 10:50:49,564] Trial 67 finished with value: 0.8740776494405106 and parameters: {'n_estimators': 109, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 66 with value: 0.9580384091817499.


Best trial: 66. Best value: 0.958038:  69%|██████▉   | 69/100 [04:23<01:02,  2.01s/it]

[I 2026-08-23 10:50:51,579] Trial 68 finished with value: 0.9566660102364648 and parameters: {'n_estimators': 123, 'max_depth': 22, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 66 with value: 0.9580384091817499.


Best trial: 66. Best value: 0.958038:  70%|███████   | 70/100 [04:24<00:55,  1.84s/it]

[I 2026-08-23 10:50:53,016] Trial 69 finished with value: 0.9506242712518853 and parameters: {'n_estimators': 81, 'max_depth': 25, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 66 with value: 0.9580384091817499.


Best trial: 66. Best value: 0.958038:  71%|███████   | 71/100 [04:27<00:59,  2.05s/it]

[I 2026-08-23 10:50:55,554] Trial 70 finished with value: 0.9559624368188135 and parameters: {'n_estimators': 159, 'max_depth': 20, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 66 with value: 0.9580384091817499.


Best trial: 66. Best value: 0.958038:  72%|███████▏  | 72/100 [04:29<00:58,  2.08s/it]

[I 2026-08-23 10:50:57,704] Trial 71 finished with value: 0.9548901171897418 and parameters: {'n_estimators': 130, 'max_depth': 26, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 66 with value: 0.9580384091817499.


Best trial: 66. Best value: 0.958038:  73%|███████▎  | 73/100 [04:32<01:01,  2.30s/it]

[I 2026-08-23 10:51:00,506] Trial 72 finished with value: 0.9569586053058877 and parameters: {'n_estimators': 177, 'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 66 with value: 0.9580384091817499.


Best trial: 66. Best value: 0.958038:  74%|███████▍  | 74/100 [04:35<01:04,  2.46s/it]

[I 2026-08-23 10:51:03,365] Trial 73 finished with value: 0.9254978531011817 and parameters: {'n_estimators': 174, 'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 66 with value: 0.9580384091817499.


Best trial: 66. Best value: 0.958038:  75%|███████▌  | 75/100 [04:37<01:01,  2.48s/it]

[I 2026-08-23 10:51:05,865] Trial 74 finished with value: 0.9571882871988922 and parameters: {'n_estimators': 156, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 66 with value: 0.9580384091817499.


Best trial: 66. Best value: 0.958038:  76%|███████▌  | 76/100 [04:39<00:54,  2.29s/it]

[I 2026-08-23 10:51:07,722] Trial 75 finished with value: 0.9516952825993856 and parameters: {'n_estimators': 113, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 66 with value: 0.9580384091817499.


Best trial: 66. Best value: 0.958038:  77%|███████▋  | 77/100 [04:41<00:47,  2.08s/it]

[I 2026-08-23 10:51:09,315] Trial 76 finished with value: 0.9561317196436369 and parameters: {'n_estimators': 92, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 66 with value: 0.9580384091817499.


Best trial: 77. Best value: 0.958931:  78%|███████▊  | 78/100 [04:43<00:44,  2.03s/it]

[I 2026-08-23 10:51:11,231] Trial 77 finished with value: 0.9589305005734857 and parameters: {'n_estimators': 134, 'max_depth': 23, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 77 with value: 0.9589305005734857.


Best trial: 77. Best value: 0.958931:  79%|███████▉  | 79/100 [04:44<00:42,  2.00s/it]

[I 2026-08-23 10:51:13,174] Trial 78 finished with value: 0.9530770422268602 and parameters: {'n_estimators': 142, 'max_depth': 23, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 77 with value: 0.9589305005734857.


Best trial: 77. Best value: 0.958931:  80%|████████  | 80/100 [04:45<00:33,  1.67s/it]

[I 2026-08-23 10:51:14,071] Trial 79 finished with value: 0.9452059119959166 and parameters: {'n_estimators': 56, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 77 with value: 0.9589305005734857.


Best trial: 77. Best value: 0.958931:  81%|████████  | 81/100 [04:48<00:34,  1.83s/it]

[I 2026-08-23 10:51:16,253] Trial 80 finished with value: 0.9541508338149769 and parameters: {'n_estimators': 162, 'max_depth': 22, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 77 with value: 0.9589305005734857.


Best trial: 77. Best value: 0.958931:  82%|████████▏ | 82/100 [04:50<00:36,  2.01s/it]

[I 2026-08-23 10:51:18,687] Trial 81 finished with value: 0.9584100023907173 and parameters: {'n_estimators': 177, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 77 with value: 0.9589305005734857.


Best trial: 77. Best value: 0.958931:  83%|████████▎ | 83/100 [04:52<00:33,  1.97s/it]

[I 2026-08-23 10:51:20,556] Trial 82 finished with value: 0.9581463997839682 and parameters: {'n_estimators': 134, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 77 with value: 0.9589305005734857.


Best trial: 77. Best value: 0.958931:  84%|████████▍ | 84/100 [04:54<00:30,  1.92s/it]

[I 2026-08-23 10:51:22,353] Trial 83 finished with value: 0.9575787154765693 and parameters: {'n_estimators': 133, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 77 with value: 0.9589305005734857.


Best trial: 77. Best value: 0.958931:  85%|████████▌ | 85/100 [04:56<00:28,  1.90s/it]

[I 2026-08-23 10:51:24,226] Trial 84 finished with value: 0.9570519741443978 and parameters: {'n_estimators': 134, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 77 with value: 0.9589305005734857.


Best trial: 77. Best value: 0.958931:  86%|████████▌ | 86/100 [04:58<00:27,  1.94s/it]

[I 2026-08-23 10:51:26,249] Trial 85 finished with value: 0.9547081039911967 and parameters: {'n_estimators': 143, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 77 with value: 0.9589305005734857.


Best trial: 77. Best value: 0.958931:  87%|████████▋ | 87/100 [04:59<00:22,  1.70s/it]

[I 2026-08-23 10:51:27,405] Trial 86 finished with value: 0.9559600882566944 and parameters: {'n_estimators': 73, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 77 with value: 0.9589305005734857.


Best trial: 77. Best value: 0.958931:  88%|████████▊ | 88/100 [05:01<00:24,  2.01s/it]

[I 2026-08-23 10:51:30,143] Trial 87 finished with value: 0.9578946882430645 and parameters: {'n_estimators': 200, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 77 with value: 0.9589305005734857.


Best trial: 77. Best value: 0.958931:  89%|████████▉ | 89/100 [05:04<00:24,  2.24s/it]

[I 2026-08-23 10:51:32,916] Trial 88 finished with value: 0.957369487123873 and parameters: {'n_estimators': 204, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 77 with value: 0.9589305005734857.


Best trial: 77. Best value: 0.958931:  90%|█████████ | 90/100 [05:07<00:24,  2.41s/it]

[I 2026-08-23 10:51:35,716] Trial 89 finished with value: 0.9546992679203608 and parameters: {'n_estimators': 210, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 77 with value: 0.9589305005734857.


Best trial: 90. Best value: 0.958936:  91%|█████████ | 91/100 [05:10<00:23,  2.56s/it]

[I 2026-08-23 10:51:38,627] Trial 90 finished with value: 0.95893564423585 and parameters: {'n_estimators': 220, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 90 with value: 0.95893564423585.


Best trial: 90. Best value: 0.958936:  92%|█████████▏| 92/100 [05:13<00:21,  2.68s/it]

[I 2026-08-23 10:51:41,582] Trial 91 finished with value: 0.9573620887125807 and parameters: {'n_estimators': 227, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 90 with value: 0.95893564423585.


Best trial: 90. Best value: 0.958936:  93%|█████████▎| 93/100 [05:16<00:18,  2.69s/it]

[I 2026-08-23 10:51:44,311] Trial 92 finished with value: 0.9576027542866269 and parameters: {'n_estimators': 203, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 90 with value: 0.95893564423585.


Best trial: 90. Best value: 0.958936:  94%|█████████▍| 94/100 [05:18<00:15,  2.64s/it]

[I 2026-08-23 10:51:46,836] Trial 93 finished with value: 0.9560169010386556 and parameters: {'n_estimators': 183, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 90 with value: 0.95893564423585.


Best trial: 90. Best value: 0.958936:  95%|█████████▌| 95/100 [05:21<00:13,  2.74s/it]

[I 2026-08-23 10:51:49,812] Trial 94 finished with value: 0.95893564423585 and parameters: {'n_estimators': 220, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 90 with value: 0.95893564423585.


Best trial: 90. Best value: 0.958936:  96%|█████████▌| 96/100 [05:24<00:11,  2.78s/it]

[I 2026-08-23 10:51:52,694] Trial 95 finished with value: 0.95893564423585 and parameters: {'n_estimators': 220, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 90 with value: 0.95893564423585.


Best trial: 90. Best value: 0.958936:  97%|█████████▋| 97/100 [05:27<00:08,  2.74s/it]

[I 2026-08-23 10:51:55,331] Trial 96 finished with value: 0.9536159609082717 and parameters: {'n_estimators': 199, 'max_depth': 16, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 90 with value: 0.95893564423585.


Best trial: 90. Best value: 0.958936:  98%|█████████▊| 98/100 [05:29<00:05,  2.77s/it]

[I 2026-08-23 10:51:58,186] Trial 97 finished with value: 0.9361227175621555 and parameters: {'n_estimators': 220, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 90 with value: 0.95893564423585.


Best trial: 90. Best value: 0.958936:  99%|█████████▉| 99/100 [05:33<00:02,  2.91s/it]

[I 2026-08-23 10:52:01,422] Trial 98 finished with value: 0.9584126172532216 and parameters: {'n_estimators': 245, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 90 with value: 0.95893564423585.


Best trial: 90. Best value: 0.958936: 100%|██████████| 100/100 [05:36<00:00,  3.36s/it]

[I 2026-08-23 10:52:04,557] Trial 99 finished with value: 0.9541366201898321 and parameters: {'n_estimators': 239, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 90 with value: 0.95893564423585.
Best trial: 
Value(macro f1):  0.95893564423585
Params: 
n_estimators: 220
max_depth: 15
min_samples_split: 3
min_samples_leaf: 1
max_features: sqrt
bootstrap: False
criterion: gini


In [ ]:
# Trial final model with best params and full training data, then evaluate on test
best_params = {
    'n_estimators': 220,
    'max_depth': 15,
    'min_samples_split': 3,
    'min_samples_leaf': 1,
    'max_features': 'sqrt',
    'bootstrap': False,
    'criterion': 'gini',
    'random_state': 42,
    'n_jobs': -1
}

final_rf = RandomForestClassifier(**best_params)
final_rf.fit(X_train_res, y_train_res) # Resampled training set
y_pred_test = final_rf.predict(X_test_new)

labels = np.arange(len(le.classes_))

print(
    "Classification Report:\n",
    classification_report(
        y_test_new,
        y_pred_test,
        labels=labels,
        target_names=le.classes_,
        zero_division=0
    )
)

print(
    "Confusion Matrix:\n",
    confusion_matrix(y_test_new, y_pred_test, labels=labels)
)

print("Accuracy:", accuracy_score(y_test_new, y_pred_test))
print("Macro F1:", f1_score(y_test_new, y_pred_test, average="macro"))


Classification Report:
               precision    recall  f1-score   support

        High       0.71      0.25      0.37        20
         Low       0.75      0.58      0.66        65
      Medium       0.88      0.95      0.91       315

    accuracy                           0.86       400
   macro avg       0.78      0.60      0.65       400
weighted avg       0.85      0.86      0.84       400

Confusion Matrix:
 [[  5   0  15]
 [  0  38  27]
 [  2  13 300]]
Accuracy: 0.8575
Macro F1: 0.646261597765298
